import React from 'react';
import RecipeItem from '../components/RecipeItem';

import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

const RecipeItemList = () => {

    const recipes = [
        {
            "idMeal": "52768",
            "strMeal": "Apple Frangipan Tart",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "British",
            "strInstructions": "Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
            "strTags": "Tart,Baking,Fruity",
            "strYoutube": "https://www.youtube.com/watch?v=rp8Slv4INLk",
            "strIngredient1": "digestive biscuits",
            "strIngredient2": "butter",
            "strIngredient3": "Bramley apples",
            "strIngredient4": "butter, softened",
            "strIngredient5": "caster sugar",
            "strIngredient6": "free-range eggs, beaten",
            "strIngredient7": "ground almonds",
            "strIngredient8": "almond extract",
            "strIngredient9": "flaked almonds",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": null,
            "strIngredient17": null,
            "strIngredient18": null,
            "strIngredient19": null,
            "strIngredient20": null,
            "strMeasure1": "175g/6oz",
            "strMeasure2": "75g/3oz",
            "strMeasure3": "200g/7oz",
            "strMeasure4": "75g/3oz",
            "strMeasure5": "75g/3oz",
            "strMeasure6": "2",
            "strMeasure7": "75g/3oz",
            "strMeasure8": "1 tsp",
            "strMeasure9": "50g/1¾oz",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": null,
            "strMeasure17": null,
            "strMeasure18": null,
            "strMeasure19": null,
            "strMeasure20": null,
            "strSource": null,
            "dateModified": null
        }, 
        {
            "idMeal": "52893",
            "strMeal": "Apple & Blackberry Crumble",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "British",
            "strInstructions": "Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.\r\nMeanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.\r\nTo serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg",
            "strTags": "Pudding",
            "strYoutube": "https://www.youtube.com/watch?v=4vhcOwVBDO4",
            "strIngredient1": "Plain Flour",
            "strIngredient2": "Caster Sugar",
            "strIngredient3": "Butter",
            "strIngredient4": "Braeburn Apples",
            "strIngredient5": "Butter",
            "strIngredient6": "Demerara Sugar",
            "strIngredient7": "Blackberrys",
            "strIngredient8": "Cinnamon",
            "strIngredient9": "Ice Cream",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "120g",
            "strMeasure2": "60g",
            "strMeasure3": "60g",
            "strMeasure4": "300g",
            "strMeasure5": "30g",
            "strMeasure6": "30g",
            "strMeasure7": "120g",
            "strMeasure8": "¼ teaspoon",
            "strMeasure9": "to serve",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble",
            "dateModified": null
        },
        {
            "idMeal": "53013",
            "strMeal": "Big Mac",
            "strDrinkAlternate": null,
            "strCategory": "Beef",
            "strArea": "American",
            "strInstructions": "For the Big Mac sauce, combine all the ingredients in a bowl, season with salt and chill until ready to use.\r\n2. To make the patties, season the mince with salt and pepper and form into 4 balls using about 1/3 cup mince each. Place each onto a square of baking paper and flatten to form into four x 15cm circles. Heat oil in a large frypan over high heat. In 2 batches, cook beef patties for 1-2 minutes each side until lightly charred and cooked through. Remove from heat and keep warm. Repeat with remaining two patties.\r\n3. Carefully slice each burger bun into three acrossways, then lightly toast.\r\n4. To assemble the burgers, spread a little Big Mac sauce over the bottom base. Top with some chopped onion, shredded lettuce, slice of cheese, beef patty and some pickle slices. Top with the middle bun layer, and spread with more Big Mac sauce, onion, lettuce, pickles, beef patty and then finish with more sauce. Top with burger lid to serve.\r\n5. After waiting half an hour for your food to settle, go for a jog.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=C5J39YnnPsg",
            "strIngredient1": "Minced Beef",
            "strIngredient2": "Olive Oil",
            "strIngredient3": "Sesame Seed Burger Buns",
            "strIngredient4": "Onion",
            "strIngredient5": "Iceberg Lettuce",
            "strIngredient6": "Cheese",
            "strIngredient7": "Dill Pickles",
            "strIngredient8": "Mayonnaise",
            "strIngredient9": "White Wine Vinegar",
            "strIngredient10": "Pepper",
            "strIngredient11": "Mustard",
            "strIngredient12": "Onion Salt",
            "strIngredient13": "Garlic Powder",
            "strIngredient14": "Paprika",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "400g",
            "strMeasure2": "2 tbs",
            "strMeasure3": "2",
            "strMeasure4": "Chopped",
            "strMeasure5": "1/4 ",
            "strMeasure6": "2 sliced",
            "strMeasure7": "2 large",
            "strMeasure8": "1 cup ",
            "strMeasure9": "2 tsp",
            "strMeasure10": "Pinch",
            "strMeasure11": "2 tsp",
            "strMeasure12": "1 1/2 tsp ",
            "strMeasure13": "1 1/2 tsp ",
            "strMeasure14": "1/2 tsp",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e",
            "dateModified": null
        },
        {
            "idMeal": "52764",
            "strMeal": "Garides Saganaki",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "Greek",
            "strInstructions": "Place the prawns in a pot and add enough water to cover. Boil for 5 minutes. Drain, reserving the liquid, and set aside.\r\nHeat 2 tablespoons of oil in a saucepan. Add the onion; cook and stir until soft. Mix in the parsley, wine, tomatoes, garlic and remaining olive oil. Simmer, stirring occasionally, for about 30 minutes, or until the sauce is thickened.\r\nWhile the sauce is simmering, the prawns should become cool enough to handle. First remove the legs by pinching them, and then pull off the shells, leaving the head and tail on.\r\nWhen the sauce has thickened, stir in the prawns. Bring to a simmer again if the sauce has cooled with the prawns, and cook for about 5 minutes. Add the feta and remove from the heat. Let stand until the cheese starts to melt. Serve warm with slices of crusty bread.\r\nThough completely untraditional, you can add a few tablespoons of stock or passata to this recipe to make a delicious pasta sauce. Toss with pasta after adding the feta, and serve.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg",
            "strTags": "Seafood,Shellfish",
            "strYoutube": "https://www.youtube.com/watch?v=uO0ejc85zSE",
            "strIngredient1": "Raw king prawns",
            "strIngredient2": "Olive oil",
            "strIngredient3": "Chopped onion",
            "strIngredient4": "Freshly chopped parsley",
            "strIngredient5": "White wine",
            "strIngredient6": "Chopped tomatoes",
            "strIngredient7": "Minced garlic",
            "strIngredient8": "Cubed Feta cheese",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": null,
            "strIngredient17": null,
            "strIngredient18": null,
            "strIngredient19": null,
            "strIngredient20": null,
            "strMeasure1": "500g",
            "strMeasure2": "3 tablespoons",
            "strMeasure3": "1",
            "strMeasure4": "pinch",
            "strMeasure5": "250ml",
            "strMeasure6": "1 (400g) tin",
            "strMeasure7": "1/2 teaspoon",
            "strMeasure8": "1 (200g) pack",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": null,
            "strMeasure17": null,
            "strMeasure18": null,
            "strMeasure19": null,
            "strMeasure20": null,
            "strSource": null,
            "dateModified": null
        }];

    return (
        <Container fluid>
            <h1>This is the RecipeItemList component</h1>
            <Row>
                {recipes.map((recipe) => {
                    return (<Col key={recipe.idMeal}><RecipeItem recipe={recipe}/></Col>)
                })}
            </Row>
        </Container>
    )
}

export default RecipeItemList;